team:
   name: Cloudly
   members:
      - user: jd.riosn1
        percentage: 25
      - user: hvlopez
        percentage: 25
      - user: l.carretero
        percentage: 25
      - user: f.fernandezr
        percentage: 25
board: https://github.com/orgs/uniandes-isis2603/projects/1
docs: https://uniandes-isis2603.github.io/s202514-proyecto-grupo17/
url: http://af76458205ead4bf8a0fdddefff42534-1939891627.us-east-1.elb.amazonaws.com
cluster_name: dann-cluster
users_app:
  folder: users_app
  image_name: users-app
  image_tag: v1.0.0
  authors:
    - jd.riosn1
posts_app:
  folder: posts_app
  image_name: posts-app
  image_tag: v1.0.0
  authors:
    - hvlopez
offers_app:
  folder: offers_app
  image_name: offers-app
  image_tag: v1.0.0
  authors:
    - l.carretero
routes_app:
  folder: routes_app
  image_name: routes-app
  image_tag: v1.0.0
  authors:
    - f.fernandezr
scores_app:
    folder: scores_app
    image_name: scores-app
    image_tag: v1.0.0
    authors:
      - jd.riosn1
rf003:
     folder: aggregator-app
     image_name: aggregator-app
     image_tag: latest
     authors:
       - l.carretero
rf005:
     folder: aggregator-app
     image_name: aggregator-app
     image_tag: latest
     authors:
       - jd.riosn1
rf004:
     folder: aggregator-app
     image_name: aggregator-app
     image_tag: latest
     authors:
       - f.fernandezr
rf006:
     folder: credit_cards_app
     image_name: credit-cards-app
     image_tag: latest
     authors:
       - l.carretero
rf007:
     folder: users-app
     image_name: users-app
     image_tag: latest
     authors:
       - jd.riosn1
